[package]
name = "cargo-execute"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "A Cargo subcommand to execute a command in the context of a Cargo project."
license = "MIT OR Apache-2.0"
repository = "https://github.com/patr-cloud/cargo-execute"
